### ISSUE TITLE
Feature: Add API for making a property `override`

### ISSUE THREAD

**Issue by zsr2531** [dansiegel/CodeGenHelpers#13]
**Summary**: Add an `Override` method to `PropertyBuilder`, similar to the one in `MethodBuilder`.

**Comment by zsr2531** [comment]
Currently, a workaround is to do [this](https://github.com/zsr2531/Bali/blob/c18944ed6fa27e4d22b1b9bdca3b34ff02aea435/src/Bali.SourceGenerators/BuilderGenerator.cs#L112), but it is not nice! :laughing:

**Comment by dansiegel** [comment]
sounds like an awesome PR :)

**Comment by zsr2531** [comment]
Done! :)
