### ISSUE TITLE
Feature: Expose `_parameters` in `MethodBuilder`

### ISSUE THREAD

**Issue by zsr2531** [dansiegel/CodeGenHelpers#14]
**Summary**: There is no way to get the parameters of a method, so maybe make that field a public property instead?

**Comment by zsr2531** [comment]
A *very* nasty workaround to solve this issue is to use [reflection](https://github.com/zsr2531/Bali/blob/530a15666d39f27e97c1a3ae3e8ca889383ef1b6/src/Bali.SourceGenerators/Builders/TypeProcessor.cs#L116), but yeah...

**Comment by dansiegel** [comment]
what is the purpose of making the parameters public? it'd be helpful to know the problem you're looking to solve there

**Comment by zsr2531** [comment]
For my use case, I am using this library to create classes that read/write JVM attributes. If my generator encounters a non-primitive typed property (ie. a user defined class or a List<T> for example), it creates a `BuildX` method so that the generated code looks nicer and conforms to the style of builders/factories that are written by hand. ([example](https://github.com/zsr2531/Bali/blob/master/src/Bali/Metadata/Builders/CodeAttributeBuilder.cs)) Obviously, I don't want to generate 2 methods for the same type, as that would result in invalid code. So I check if there has already been a method generated for it. ([example](https://github.com/zsr2531/Bali/blob/530a15666d39f27e97c1a3ae3e8ca889383ef1b6/src/Bali.SourceGenerators/Builders/TypeProcessor.cs#L64))
