### ISSUE TITLE
`ISymbolExtensions` are only compiled if `TEST` constant is set.

### ISSUE THREAD

**Issue by zsr2531** [dansiegel/CodeGenHelpers#16]
**Summary**: I get compile errors because the configuration doesn't have `TEST` defined.
**Affected files**:
- [ISymbolExtensions.cs](https://github.com/dansiegel/CodeGenHelpers/blob/aaf9ca7eda8a08719289c29186a103489e786ebf/src/CodeGenHelpers/Extensions/ISymbolExtensions.cs#L1)
- [CodeBuilderExtensions.cs](https://github.com/dansiegel/CodeGenHelpers/blob/aaf9ca7eda8a08719289c29186a103489e786ebf/src/CodeGenHelpers/CodeBuilderExtensions.cs#L35) <- compile error occurs here

**Comment by dansiegel** [comment]
You'll need to define the constant in your project. This works with the Uno.SoureGeneration which actually provides these extensions out of the box. I am open to renaming it but not removing the exclusion.

**Comment by zsr2531** [comment]
How about `INCLUDE_EXTENSIONS` or `EXTENSIONS`? I can create a PR to change it if you are happy with one of those.

**Comment by zsr2531** [comment]
Another option could be to make the extensions `internal`, but it's up to you to decide.

**Comment by dansiegel** [comment]
I'm currently evaluating just shipping this via NuGet... if I do that making them internal would be the way to go
