### ISSUE TITLE
Add helper methods 

### ISSUE THREAD

**Issue by pictos** [dansiegel/CodeGenHelpers#25]
This could be an `Epic`

During a Source Generator development, we need to perform some tasks like:

- Get a value of an Attribute property;
- Get a declaration Syntax or Symbol;
- Format a source code string, using the `editorconfig` of the target project;
- Get the information of an Attribute property.

Having some helper methods that do this repetitively will add great value.

Some examples of extension methods:

```csharp
TSymbol GetSymbol<TSymbol>(Compilation compilation, BaseTypeDeclarationSyntax declarationSyntax);
static void FormatText(ref string classSource, CSharpParseOptions options);
TypedConstant GetAttributeValueByName(this AttributeData attribute, string name);
string GetAttributeValueByNameAsString(this AttributeData attribute, string name, string placeholder = "null");
```

Usage:

```csharp

// In Source Generator consumer code
[BP(PropertyName = "TextColor")]


//In Source Generator code
// With this helper method I'll be able to get the `PropertyName` in one line of code.
var propName = attribute.GetAttributeValueByNameAsString("PropertyName");
```

**Comment by dansiegel** [comment]
can you expand on this idea into more of a spec... how we would perhaps use these "helper methods", what you're generating...

**Comment by pictos** [comment]
@dansiegel I've updated the problem description with a more general idea, if it still seems confusing I'll convert this into an implementation of a helper method.

**Comment by dansiegel** [comment]
sorry this seems to have slipped through the cracks @pictos... if you wanted to put together a PR I'd be more than happy to merge it.

**Comment by dansiegel** [comment]
I am curious what you are thinking for this. Though I think this is probably the wrong application. My assumption is that you want to perhaps determine if you can do things like Top Level namespaces or whether it should be using Tabs/Spaces? If that's the case this would be better as an optional parameter when creating the CodeWriter to begin with.
```cs
static void FormatText(ref string classSource, CSharpParseOptions options);
```

**Comment by pictos** [comment]
@dansiegel so, with this method we don't need to care about `code-style` (indentation, tab/space, braces in new line, etc) during the code generation, and we generate all the string we call this method, then it will apply the code style that the project uses.
You can see how it's implemented [here](https://github.com/CommunityToolkit/Maui/blob/main/src/CommunityToolkit.Maui.SourceGenerators/Helpers/SourceStringExtensions.cs)
