### ISSUE TITLE
Add support for generics

### ISSUE THREAD

**Issue by MichaelHochriegl** [dansiegel/CodeGenHelpers#26]
Thanks for this awesome project!

However I looked around and couldn't find a way to add a generic to either a class or a method.
If there is, sorry for being blind.

But if their isn't: Would be pretty handy to have this functionality.
I'm willing to look at this myself and do a Pull Request, but it would be nice if there would be some guidance on how you would want this feature to be implemented.

**Comment by dansiegel** [comment]
@MichaelHochriegl if you'd like to come up with a spec of what the API would look like we can certainly go from there.

**Comment by MichaelHochriegl** [comment]
I will start looking at this in the next couple of days. Will do a Pull Request once I'm done (time depends on the changes requested in my other Pull Request #27 )

**Comment by MichaelHochriegl** [comment]
I've got the generic class working, but I don't know if this is "good" system I've come up with. I've pushed my current implementation to my fork ([https://github.com/MichaelHochriegl/CodeGenHelpers/tree/feature/generics](https://github.com/MichaelHochriegl/CodeGenHelpers/tree/feature/generics), but I'm really not too happy with this.

Any insight on how I should improve it?
I kinda butchered the ClassBuilder.Write method.

**Comment by dansiegel** [comment]
@MichaelHochriegl why don't we start with this... The CodeGenHelpers is all about providing a nice fluent builder API... so the first question to ask is what does that look like for what you want the new API to look like.

**Comment by MichaelHochriegl** [comment]
My API approach would look like this:
```csharp
var builder = CodeBuilder.Create("AwesomeApp")
                .AddClass("SampleGenericClass")
                .AddGeneric("T")
                    .WithConstraint("class")
                    .Parent
                .AddGeneric("U")
                    .WithConstraint("class")
                    .Parent
                .AddGeneric("K")
                    .Parent
                .AddMethod("MyGenericMethod")
                    .AddGeneric("V")
                    .WithConstraint("class")
                    .Class;
```
This would be the way to add a generic to a class. This should generate a class with this structure:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeApp
{
    partial class SampleGenericClass <T, U, K> : where T : class where U : class
    {
        void MyGenericMethod<V>() where V : class
        {
        }
    }
}
```
I hope that this is fluent-enough.
For this I would create a class `GenericBuilder<T> where T : BuilderBase<T>` and add the stuff similar to the other Builders.

**Comment by dansiegel** [comment]
For reference, the API currently doesn't directly allow you to specify Generic Parameters. I do believe the proposal outlined here with the following modifications is an improvement well worth while. It is important to note though that currently there is limited capability by including the parameters as part of your Class/Method name. You can also add the Constraints.

I believe the API we would want is more along the lines of this:

```cs
var builder = CodeBuilder.Create("AwesomeApp")
                .AddClass("SampleGenericClass")
                .AddGeneric("T", c => {
                    c.New();
                    c.Class();
                })
                .AddGeneric("U")
                .AddGeneric("K")
                .AddMethod("MyGenericMethod")
                    .AddGeneric("V", c => c.Constraint("ISomeInterface"))
                    .Class;
```

My thinking is that realistically the only thing that you might want to do on a Generic definition is add a constraint. We can easily expose this through an optional delegate to configure the builder without overly complicating the Fluent API

```cs
namespace AwesomeApp
{
    public class SampleGenericClass<T, U, K>
        where T : new(), class
    {
        public void MyGenericMethod<V>()
            where V : ISomeInterface
        {

        }
    }
}
```

I will be pushing a PR for this soon
