### ISSUE TITLE
Racecondition fails test (triggered by debugging)

### ISSUE THREAD

**Issue by MichaelHochriegl** [dansiegel/CodeGenHelpers#33]
As I've been working on the RecordBuilder I noticed that I can force a racecondition which will produce a wrong output.
After looking at my code I've noticed that I can reproduce it on any test.

To reproduce this issue I did the following:

1. Place breakpoint in `CodeBuilder` on line 107 and line 140
2. Execute a test (e.g. `PropertyTests.GenerateAutoProperty`) in debug
3. When hitting the breakpoint in line 107 wait a couple of seconds
4. Resume to hit the breakpoint on line 140
5. Resume the execution and the test will fail

Screenshot to see the breakpoints:
![grafik](https://user-images.githubusercontent.com/78933445/155767384-4d978eff-ed08-439a-84c7-f43b59bdc8ff.png)

If you inspect the writer output in debug view on step 4 the generated code is:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeApp
{
}

```

The actual generated output after step 5 will be:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeApp
{
}
partial class SampleClass
{
    string Test { get; set; }
}

```

The actual class/record is placed outside of the namespace curly braces.
This behaviour happens on the master-branch.

**Comment by dansiegel** [comment]
I'm going to close this as I have not been able to reproduce the issue. Also the CodeGenHelpers are being used by a number of generators writing A LOT of code at this point without issue. If the problem persists or you are able to debug and provide a fix for please feel free to let me know and submit a PR.
