### ISSUE TITLE
bug: MethodBuilder disposes CodeWriter after writing first method closing the class and namespace prematurely

### ISSUE THREAD

**Issue by niklasstich** [dansiegel/CodeGenHelpers#42]
MethodBuilder obtains an IDisposable handle on the currently being used CodeWriter at the end of its write method by calling `writer.Block` on it in a using statement (see [here](https://github.com/dansiegel/CodeGenHelpers/blob/b3f55795d5f424cff425e99d36ccfecf6efb6943/src/CodeGenHelpers/MethodBuilder.cs#L240)), before invoking `_methodBodyWriter` and ultimately disposing the CodeWriter afterwards. Because of the changes introduced to the Dispose method of CodeWriter in 9963d789623770bd830ba4fdda422223f05960b9, this immediately closes off not only the currently being written to method block, but also the class and namespace blocks. This means that all following Writers write outside of the namespace block, leading to incorrect code. 

I can share a minimum reproducible example if necessary, but it should be immediately obvious when trying to generate any class with a method. It would probably be prudent to add a test case with multiple methods to check for this in the future.

Example diff from my project after updating: 
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/32730297/194737470-b406d866-dabe-43a6-bdc8-649775240df3.png">

**Comment by dansiegel** [comment]
Thanks for the report. I've unlisted the package and will try to get a fix out shortly
