### ISSUE TITLE
Ship V2 as a source generator instead of a library

### ISSUE THREAD

**Issue by Blackclaws** [dansiegel/CodeGenHelpers#67]
Adding libraries to source generators as dependencies is notoriously hard:

https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#use-functionality-from-nuget-packages

And it gets worse if multiple generators use the same library but in different versions as roslyn does _not_ currently load them into different domains.

Instead I would suggest shipping V2 as a generator in its own right that simply adds these files post initialization so they are compiled into the source generator directly without people needing to copy things manually.

**Comment by Blackclaws** [comment]
Stacking source generators is a difficult topic and by default not even supported unless you take a direct dependency on the other source generator and then call it manually as source generators cannot see the output of other source generators.

That is however not relevant here, as I am not proposing packaging this project as an additional source generator to be applied to the final target but instead to use this project _as_ a source generator _for_ a source generator. Meaning the generated source will be compiled into the generator and just be part of it as if you copied the files in.

This is not stacking source generators at all.

**Comment by MichaelHochriegl** [comment]
Ah, sorry, I must have misunderstood your approach than. I played around with SGs a little more and get your solution now. Thanks for clarification.

**Comment by dansiegel** [comment]
We've come up with a solution that provides for adaptability by default this will install as a library reference in your project. Thanks to @jeromelaban we have introduced control over whether to reference this as a library or source code via an MSBuild property.

```txt
The CodeGenHelpers come in two flavors, set using `CodeGenHelpersMode`:
- `Assembly`, in order to be used as a normal assembly
- `Source`, where the helpers are linked as source files to eliminate issues with assembly references.
```
